- name: play1
  hosts: all
  tasks:
  - name: Run command
    command: rm jenkins.war chdir:/home/osboxes/
  - name: Copy File
    copy:
     src: /home/osboxes/jenkins/jenkins.war
     dest: /home/osboxes/